name: Publish V2 Docs

on:
  push:
    tags:
      - "docs-v2-r*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: |
          yarn install
          yarn prepack
          yarn docs
          tar czvf ${{ github.ref_name }}.apidocs.tgz -C docs api
        env:
          NODE_OPTIONS: --max_old_space_size=8192

      - run: |
          cd website
          yarn install
          yarn build:local
          tar czvf ${{ github.ref_name }}.website.local.tgz -C build/local site
          rm -rf .docusaurus
          yarn build:prod
          tar czvf ${{ github.ref_name }}.website.prod.tgz -C build/prod site
          cp *.tgz ..

      - run: node -pe '`relnum=${"${{ github.ref_name }}".substring("docs-v2-r".length)}`' >> $GITHUB_OUTPUT
        id: relnum

      - uses: ncipollo/release-action@v1
        with:
          name: V2 Documentation R${{ steps.relnum.outputs.relnum }}
          body: Website and API documentation for Effection V2 (R${{ steps.relnum.outputs.relnum  }})
          artifacts: "*.tgz"
          token: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
